name: wizard
description: If you can guess what was a weekday of random date a few times in a row, then you are a fucking Wizard!
version: 0.0.0
# homepage: https://www.example.com
author: Anton Siluev <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
